version: 2
jobs:
  build:
    docker:
      - image: nemuframework/gcc-nemu-cpp:0.18.0
    steps:
      - run:
          name: Add GitHub SSH fingerprints
          command: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "Set CODESMITHYIDE environment variables and create workspace directory"
          command: mkdir -p /projects/codesmithyide && echo 'export CODESMITHYIDE="/projects/codesmithyide"' >> $BASH_ENV
      - run:
          name: "Install build dependency: CodeSmithyDoxygenCore"
          command: cd /projects/codesmithyide && git clone git@github.com:codesmithyide/doxygen.git && cd doxygen/core/build/gnumake && make
      - checkout:
          path: /projects/codesmithyide/content-platform
      - run:
          name: Build CodeSmithyContentPlatformCore library
          command: cd /projects/codesmithyide/content-platform/core/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/codesmithyide/content-platform/core/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/codesmithyide/content-platform/core/tests/build/gnumake && ./CodeSmithyContentPlatformCoreTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyContentPlatformCore.xml
      - store_artifacts:
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          path: /build/test-results/CodeSmithyContentPlatformCore.xml
          destination: CodeSmithyContentPlatformCore-test-results.xml
      - store_test_results:
          path: /build/test-results/CodeSmithyContentPlatformCore.xml
      - run:
          name: Build CodeSmithyContentPlatformWebServer binary
          command: cd /projects/codesmithyide/content-platform/web-server/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
