version: 2
jobs:
  build:
    docker:
      - image: nemuframework/gcc-nemu-cpp:0.6.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /projects/codesmithyide/content-platform
      - run:
          name: Build CodeSmithyContentPlatformCore library
          command: cd /projects/codesmithyide/content-platform/core/build/gnumake && make
      - run:
          name: Build CodeSmithyContentPlatformWebServer binary
          command: cd /projects/codesmithyide/content-platform/web-server/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
